#!/bin/bash
# Script to auto-generate the Backend SDK for Node.js using OpenAPI Generator

# Use the OpenAPI JSON generated by ASP.NET Core (.NET 8 native OpenAPI)
API_URL="http://127.0.0.1:5000/swagger/v1/swagger.json"

echo "Downloading OpenAPI Spec..."
curl -k $API_URL -o openapi.json

echo "Generating Node.js SDK using OpenAPI Generator..."
npx @openapitools/openapi-generator-cli generate \
    -i openapi.json \
    -g typescript-node \
    -o ./generated \
    --additional-properties=supportsES6=true,npmName=@cpaas/backend-sdk

echo "SDK Generated successfully in ./generated"
