apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_DEPLOYMENT_MODE
          value: {{ .Values.global.mode }}
        - name: NEXT_PUBLIC_API_URL
          value: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
