domain: cpaas.178.62.192.74.nip.io
replicaCount: 1

imagePullPolicy: IfNotPresent

frontend:
  image: cpaas-frontend:latest
  port: 3000

backend:
  image: cpaas-backend:latest
  port: 8080 # ASP.NET default Docker port is 8080 in .NET 8

postgresql:
  enabled: false
  auth:
    username: postgres
    password: postgres
    database: cpaas_db

redis:
  enabled: false

minio:
  enabled: false
