apiVersion: v1
kind: Service
metadata:
  name: asterisk-headless
  namespace: default
spec:
  clusterIP: None
  selector:
    app: asterisk
  ports:
  - name: sip-udp
    port: 5060
    protocol: UDP
  - name: sip-tcp
    port: 5060
    protocol: TCP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: asterisk
  namespace: default
spec:
  serviceName: "asterisk-headless"
  replicas: 2
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image: asterisk:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5060
          name: sip-udp
          protocol: UDP
        - containerPort: 5060
          name: sip-tcp
          protocol: TCP
        volumeMounts:
        - name: asterisk-config
          mountPath: /etc/asterisk/pjsip.conf
          subPath: pjsip.conf
        - name: asterisk-config
          mountPath: /etc/asterisk/extensions.conf
          subPath: extensions.conf
      volumes:
      - name: asterisk-config
        configMap:
          name: asterisk-config
