apiVersion: v1
kind: ConfigMap
metadata:
  name: asterisk-config
  namespace: default
data:
  pjsip.conf: |
    [transport-udp]
    type=transport
    protocol=udp
    bind=0.0.0.0:5060
    local_net=10.0.0.0/8
    local_net=172.16.0.0/12
    local_net=192.168.0.0/16
    
    #include dynamic/pjsip_endpoints.conf

    
  extensions.conf: |
    [general]
    static=yes
    writeprotect=no
    
    [from-internal]
    ; If the user dials exactly 4 digits (e.g. 1234), prepend 'ext'
    exten => _XXXX,1,NoOp(Call to ext${EXTEN})
    same => n,Dial(PJSIP/ext${EXTEN})
    same => n,Hangup()
    
    ; If they dial the full name (e.g. ext1234)
    exten => _extXXXX,1,NoOp(Call to ${EXTEN})
    same => n,Dial(PJSIP/${EXTEN})
    same => n,Hangup()
    
    ; Fallback for everything else
    exten => _[a-zA-Z0-9].,1,NoOp(Call to ${EXTEN})
    same => n,Dial(PJSIP/${EXTEN})
    same => n,Hangup()
