apiVersion: apps/v1
kind: Deployment
metadata:
  name: kamailio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kamailio
  template:
    metadata:
      labels:
        app: kamailio
    spec:
      hostNetwork: true
      containers:
      - name: kamailio
        image: cpaas-kamailio:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5060
          protocol: UDP
        - containerPort: 5060
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: /etc/kamailio/kamailio.cfg
          subPath: kamailio.cfg
        - name: config
          mountPath: /etc/kamailio/dispatcher.list
          subPath: dispatcher.list
      volumes:
      - name: config
        configMap:
          name: kamailio-config
