apiVersion: v1
kind: Service
metadata:
  name: asterisk-tcp
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: asterisk
  ports:
  - name: sip-tcp
    port: 5060
    protocol: TCP
    targetPort: 5060
