apiVersion: apps/v1
kind: Deployment
metadata:
  name: asterisk
  labels:
    app: asterisk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asterisk
  template:
    metadata:
      labels:
        app: asterisk
    spec:
      containers:
      - name: asterisk
        image: asterisk:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5060
          protocol: UDP
        - containerPort: 5060
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: asterisk
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: asterisk
  ports:
  - name: sip-udp
    port: 5060
    protocol: UDP
    targetPort: 5060
