version: '3.8'
services:
  asterisk:
    build: .
    image: asterisk:latest
    container_name: asterisk
    network_mode: host
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
