[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[livekit-sip]
type=endpoint
transport=transport-udp
context=from-external
disallow=all
allow=ulaw,alaw,opus
aors=livekit-sip

[livekit-sip]
type=aor
contact=sip:livekit-sip:5060
