[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[kamailio]
type=endpoint
transport=transport-udp
context=from-kamailio
disallow=all
allow=ulaw,alaw,opus
aors=kamailio

[kamailio]
type=aor
contact=sip:kamailio:5060
